/****************************************************************************
 * arch/ceva/include/xm6/reg.h
 *
 *   Copyright (C) 2018 Pinecone Inc. All rights reserved.
 *   Author: Xiang Xiao <xiaoxiang@pinecone.net>
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name NuttX nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

#ifndef __ARCH_CEVA_INCLUDE_XM6_REG_H
#define __ARCH_CEVA_INCLUDE_XM6_REG_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* IRQ Stack Frame Format: */

/* The following registers are stored by the interrupt handling
 * logic.
 */

#define REG_SP                0
#ifdef CONFIG_ARCH_XM6_STACKCHECK
#  define REG_SB              1
#  define REG_SL              2
#  define XCPT_SP_REGS        3
#else
#  define XCPT_SP_REGS        1
#endif

#ifndef CONFIG_ARCH_XM6_NO_VPU
#  define REG_V470            (XCPT_SP_REGS + 0)
#  define REG_V471            (XCPT_SP_REGS + 1)
#  define REG_V472            (XCPT_SP_REGS + 2)
#  define REG_V473            (XCPT_SP_REGS + 3)
#  define REG_V474            (XCPT_SP_REGS + 4)
#  define REG_V475            (XCPT_SP_REGS + 5)
#  define REG_V476            (XCPT_SP_REGS + 6)
#  define REG_V477            (XCPT_SP_REGS + 7)
#  define REG_V460            (XCPT_SP_REGS + 8)
#  define REG_V461            (XCPT_SP_REGS + 9)
#  define REG_V462            (XCPT_SP_REGS + 10)
#  define REG_V463            (XCPT_SP_REGS + 11)
#  define REG_V464            (XCPT_SP_REGS + 12)
#  define REG_V465            (XCPT_SP_REGS + 13)
#  define REG_V466            (XCPT_SP_REGS + 14)
#  define REG_V467            (XCPT_SP_REGS + 15)
#  define REG_V450            (XCPT_SP_REGS + 16)
#  define REG_V451            (XCPT_SP_REGS + 17)
#  define REG_V452            (XCPT_SP_REGS + 18)
#  define REG_V453            (XCPT_SP_REGS + 19)
#  define REG_V454            (XCPT_SP_REGS + 20)
#  define REG_V455            (XCPT_SP_REGS + 21)
#  define REG_V456            (XCPT_SP_REGS + 22)
#  define REG_V457            (XCPT_SP_REGS + 23)
#  define REG_V440            (XCPT_SP_REGS + 24)
#  define REG_V441            (XCPT_SP_REGS + 25)
#  define REG_V442            (XCPT_SP_REGS + 26)
#  define REG_V443            (XCPT_SP_REGS + 27)
#  define REG_V444            (XCPT_SP_REGS + 28)
#  define REG_V445            (XCPT_SP_REGS + 29)
#  define REG_V446            (XCPT_SP_REGS + 30)
#  define REG_V447            (XCPT_SP_REGS + 31)
#  define REG_V430            (XCPT_SP_REGS + 32)
#  define REG_V431            (XCPT_SP_REGS + 33)
#  define REG_V432            (XCPT_SP_REGS + 34)
#  define REG_V433            (XCPT_SP_REGS + 35)
#  define REG_V434            (XCPT_SP_REGS + 36)
#  define REG_V435            (XCPT_SP_REGS + 37)
#  define REG_V436            (XCPT_SP_REGS + 38)
#  define REG_V437            (XCPT_SP_REGS + 39)
#  define REG_V420            (XCPT_SP_REGS + 40)
#  define REG_V421            (XCPT_SP_REGS + 41)
#  define REG_V422            (XCPT_SP_REGS + 42)
#  define REG_V423            (XCPT_SP_REGS + 43)
#  define REG_V424            (XCPT_SP_REGS + 44)
#  define REG_V425            (XCPT_SP_REGS + 45)
#  define REG_V426            (XCPT_SP_REGS + 46)
#  define REG_V427            (XCPT_SP_REGS + 47)
#  define REG_V410            (XCPT_SP_REGS + 48)
#  define REG_V411            (XCPT_SP_REGS + 49)
#  define REG_V412            (XCPT_SP_REGS + 50)
#  define REG_V413            (XCPT_SP_REGS + 51)
#  define REG_V414            (XCPT_SP_REGS + 52)
#  define REG_V415            (XCPT_SP_REGS + 53)
#  define REG_V416            (XCPT_SP_REGS + 54)
#  define REG_V417            (XCPT_SP_REGS + 55)
#  define REG_V400            (XCPT_SP_REGS + 56)
#  define REG_V401            (XCPT_SP_REGS + 57)
#  define REG_V402            (XCPT_SP_REGS + 58)
#  define REG_V403            (XCPT_SP_REGS + 59)
#  define REG_V404            (XCPT_SP_REGS + 60)
#  define REG_V405            (XCPT_SP_REGS + 61)
#  define REG_V406            (XCPT_SP_REGS + 62)
#  define REG_V407            (XCPT_SP_REGS + 63)
#  define REG_V390            (XCPT_SP_REGS + 64)
#  define REG_V391            (XCPT_SP_REGS + 65)
#  define REG_V392            (XCPT_SP_REGS + 66)
#  define REG_V393            (XCPT_SP_REGS + 67)
#  define REG_V394            (XCPT_SP_REGS + 68)
#  define REG_V395            (XCPT_SP_REGS + 69)
#  define REG_V396            (XCPT_SP_REGS + 70)
#  define REG_V397            (XCPT_SP_REGS + 71)
#  define REG_V380            (XCPT_SP_REGS + 72)
#  define REG_V381            (XCPT_SP_REGS + 73)
#  define REG_V382            (XCPT_SP_REGS + 74)
#  define REG_V383            (XCPT_SP_REGS + 75)
#  define REG_V384            (XCPT_SP_REGS + 76)
#  define REG_V385            (XCPT_SP_REGS + 77)
#  define REG_V386            (XCPT_SP_REGS + 78)
#  define REG_V387            (XCPT_SP_REGS + 79)
#  define REG_V370            (XCPT_SP_REGS + 80)
#  define REG_V371            (XCPT_SP_REGS + 81)
#  define REG_V372            (XCPT_SP_REGS + 82)
#  define REG_V373            (XCPT_SP_REGS + 83)
#  define REG_V374            (XCPT_SP_REGS + 84)
#  define REG_V375            (XCPT_SP_REGS + 85)
#  define REG_V376            (XCPT_SP_REGS + 86)
#  define REG_V377            (XCPT_SP_REGS + 87)
#  define REG_V360            (XCPT_SP_REGS + 88)
#  define REG_V361            (XCPT_SP_REGS + 89)
#  define REG_V362            (XCPT_SP_REGS + 90)
#  define REG_V363            (XCPT_SP_REGS + 91)
#  define REG_V364            (XCPT_SP_REGS + 92)
#  define REG_V365            (XCPT_SP_REGS + 93)
#  define REG_V366            (XCPT_SP_REGS + 94)
#  define REG_V367            (XCPT_SP_REGS + 95)
#  define REG_V350            (XCPT_SP_REGS + 96)
#  define REG_V351            (XCPT_SP_REGS + 97)
#  define REG_V352            (XCPT_SP_REGS + 98)
#  define REG_V353            (XCPT_SP_REGS + 99)
#  define REG_V354            (XCPT_SP_REGS + 100)
#  define REG_V355            (XCPT_SP_REGS + 101)
#  define REG_V356            (XCPT_SP_REGS + 102)
#  define REG_V357            (XCPT_SP_REGS + 103)
#  define REG_V340            (XCPT_SP_REGS + 104)
#  define REG_V341            (XCPT_SP_REGS + 105)
#  define REG_V342            (XCPT_SP_REGS + 106)
#  define REG_V343            (XCPT_SP_REGS + 107)
#  define REG_V344            (XCPT_SP_REGS + 108)
#  define REG_V345            (XCPT_SP_REGS + 109)
#  define REG_V346            (XCPT_SP_REGS + 110)
#  define REG_V347            (XCPT_SP_REGS + 111)
#  define REG_V330            (XCPT_SP_REGS + 112)
#  define REG_V331            (XCPT_SP_REGS + 113)
#  define REG_V332            (XCPT_SP_REGS + 114)
#  define REG_V333            (XCPT_SP_REGS + 115)
#  define REG_V334            (XCPT_SP_REGS + 116)
#  define REG_V335            (XCPT_SP_REGS + 117)
#  define REG_V336            (XCPT_SP_REGS + 118)
#  define REG_V337            (XCPT_SP_REGS + 119)
#  define REG_V320            (XCPT_SP_REGS + 120)
#  define REG_V321            (XCPT_SP_REGS + 121)
#  define REG_V322            (XCPT_SP_REGS + 122)
#  define REG_V323            (XCPT_SP_REGS + 123)
#  define REG_V324            (XCPT_SP_REGS + 124)
#  define REG_V325            (XCPT_SP_REGS + 125)
#  define REG_V326            (XCPT_SP_REGS + 126)
#  define REG_V327            (XCPT_SP_REGS + 127)
#  define REG_V310            (XCPT_SP_REGS + 128)
#  define REG_V311            (XCPT_SP_REGS + 129)
#  define REG_V312            (XCPT_SP_REGS + 130)
#  define REG_V313            (XCPT_SP_REGS + 131)
#  define REG_V314            (XCPT_SP_REGS + 132)
#  define REG_V315            (XCPT_SP_REGS + 133)
#  define REG_V316            (XCPT_SP_REGS + 134)
#  define REG_V317            (XCPT_SP_REGS + 135)
#  define REG_V300            (XCPT_SP_REGS + 136)
#  define REG_V301            (XCPT_SP_REGS + 137)
#  define REG_V302            (XCPT_SP_REGS + 138)
#  define REG_V303            (XCPT_SP_REGS + 139)
#  define REG_V304            (XCPT_SP_REGS + 140)
#  define REG_V305            (XCPT_SP_REGS + 141)
#  define REG_V306            (XCPT_SP_REGS + 142)
#  define REG_V307            (XCPT_SP_REGS + 143)
#  define REG_V290            (XCPT_SP_REGS + 144)
#  define REG_V291            (XCPT_SP_REGS + 145)
#  define REG_V292            (XCPT_SP_REGS + 146)
#  define REG_V293            (XCPT_SP_REGS + 147)
#  define REG_V294            (XCPT_SP_REGS + 148)
#  define REG_V295            (XCPT_SP_REGS + 149)
#  define REG_V296            (XCPT_SP_REGS + 150)
#  define REG_V297            (XCPT_SP_REGS + 151)
#  define REG_V280            (XCPT_SP_REGS + 152)
#  define REG_V281            (XCPT_SP_REGS + 153)
#  define REG_V282            (XCPT_SP_REGS + 154)
#  define REG_V283            (XCPT_SP_REGS + 155)
#  define REG_V284            (XCPT_SP_REGS + 156)
#  define REG_V285            (XCPT_SP_REGS + 157)
#  define REG_V286            (XCPT_SP_REGS + 158)
#  define REG_V287            (XCPT_SP_REGS + 159)
#  define REG_V270            (XCPT_SP_REGS + 160)
#  define REG_V271            (XCPT_SP_REGS + 161)
#  define REG_V272            (XCPT_SP_REGS + 162)
#  define REG_V273            (XCPT_SP_REGS + 163)
#  define REG_V274            (XCPT_SP_REGS + 164)
#  define REG_V275            (XCPT_SP_REGS + 165)
#  define REG_V276            (XCPT_SP_REGS + 166)
#  define REG_V277            (XCPT_SP_REGS + 167)
#  define REG_V260            (XCPT_SP_REGS + 168)
#  define REG_V261            (XCPT_SP_REGS + 169)
#  define REG_V262            (XCPT_SP_REGS + 170)
#  define REG_V263            (XCPT_SP_REGS + 171)
#  define REG_V264            (XCPT_SP_REGS + 172)
#  define REG_V265            (XCPT_SP_REGS + 173)
#  define REG_V266            (XCPT_SP_REGS + 174)
#  define REG_V267            (XCPT_SP_REGS + 175)
#  define REG_V250            (XCPT_SP_REGS + 176)
#  define REG_V251            (XCPT_SP_REGS + 177)
#  define REG_V252            (XCPT_SP_REGS + 178)
#  define REG_V253            (XCPT_SP_REGS + 179)
#  define REG_V254            (XCPT_SP_REGS + 180)
#  define REG_V255            (XCPT_SP_REGS + 181)
#  define REG_V256            (XCPT_SP_REGS + 182)
#  define REG_V257            (XCPT_SP_REGS + 183)
#  define REG_V240            (XCPT_SP_REGS + 184)
#  define REG_V241            (XCPT_SP_REGS + 185)
#  define REG_V242            (XCPT_SP_REGS + 186)
#  define REG_V243            (XCPT_SP_REGS + 187)
#  define REG_V244            (XCPT_SP_REGS + 188)
#  define REG_V245            (XCPT_SP_REGS + 189)
#  define REG_V246            (XCPT_SP_REGS + 190)
#  define REG_V247            (XCPT_SP_REGS + 191)
#  define REG_V230            (XCPT_SP_REGS + 192)
#  define REG_V231            (XCPT_SP_REGS + 193)
#  define REG_V232            (XCPT_SP_REGS + 194)
#  define REG_V233            (XCPT_SP_REGS + 195)
#  define REG_V234            (XCPT_SP_REGS + 196)
#  define REG_V235            (XCPT_SP_REGS + 197)
#  define REG_V236            (XCPT_SP_REGS + 198)
#  define REG_V237            (XCPT_SP_REGS + 199)
#  define REG_V220            (XCPT_SP_REGS + 200)
#  define REG_V221            (XCPT_SP_REGS + 201)
#  define REG_V222            (XCPT_SP_REGS + 202)
#  define REG_V223            (XCPT_SP_REGS + 203)
#  define REG_V224            (XCPT_SP_REGS + 204)
#  define REG_V225            (XCPT_SP_REGS + 205)
#  define REG_V226            (XCPT_SP_REGS + 206)
#  define REG_V227            (XCPT_SP_REGS + 207)
#  define REG_V210            (XCPT_SP_REGS + 208)
#  define REG_V211            (XCPT_SP_REGS + 209)
#  define REG_V212            (XCPT_SP_REGS + 210)
#  define REG_V213            (XCPT_SP_REGS + 211)
#  define REG_V214            (XCPT_SP_REGS + 212)
#  define REG_V215            (XCPT_SP_REGS + 213)
#  define REG_V216            (XCPT_SP_REGS + 214)
#  define REG_V217            (XCPT_SP_REGS + 215)
#  define REG_V200            (XCPT_SP_REGS + 216)
#  define REG_V201            (XCPT_SP_REGS + 217)
#  define REG_V202            (XCPT_SP_REGS + 218)
#  define REG_V203            (XCPT_SP_REGS + 219)
#  define REG_V204            (XCPT_SP_REGS + 220)
#  define REG_V205            (XCPT_SP_REGS + 221)
#  define REG_V206            (XCPT_SP_REGS + 222)
#  define REG_V207            (XCPT_SP_REGS + 223)
#  define REG_V190            (XCPT_SP_REGS + 224)
#  define REG_V191            (XCPT_SP_REGS + 225)
#  define REG_V192            (XCPT_SP_REGS + 226)
#  define REG_V193            (XCPT_SP_REGS + 227)
#  define REG_V194            (XCPT_SP_REGS + 228)
#  define REG_V195            (XCPT_SP_REGS + 229)
#  define REG_V196            (XCPT_SP_REGS + 230)
#  define REG_V197            (XCPT_SP_REGS + 231)
#  define REG_V180            (XCPT_SP_REGS + 232)
#  define REG_V181            (XCPT_SP_REGS + 233)
#  define REG_V182            (XCPT_SP_REGS + 234)
#  define REG_V183            (XCPT_SP_REGS + 235)
#  define REG_V184            (XCPT_SP_REGS + 236)
#  define REG_V185            (XCPT_SP_REGS + 237)
#  define REG_V186            (XCPT_SP_REGS + 238)
#  define REG_V187            (XCPT_SP_REGS + 239)
#  define REG_V170            (XCPT_SP_REGS + 240)
#  define REG_V171            (XCPT_SP_REGS + 241)
#  define REG_V172            (XCPT_SP_REGS + 242)
#  define REG_V173            (XCPT_SP_REGS + 243)
#  define REG_V174            (XCPT_SP_REGS + 244)
#  define REG_V175            (XCPT_SP_REGS + 245)
#  define REG_V176            (XCPT_SP_REGS + 246)
#  define REG_V177            (XCPT_SP_REGS + 247)
#  define REG_V160            (XCPT_SP_REGS + 248)
#  define REG_V161            (XCPT_SP_REGS + 249)
#  define REG_V162            (XCPT_SP_REGS + 250)
#  define REG_V163            (XCPT_SP_REGS + 251)
#  define REG_V164            (XCPT_SP_REGS + 252)
#  define REG_V165            (XCPT_SP_REGS + 253)
#  define REG_V166            (XCPT_SP_REGS + 254)
#  define REG_V167            (XCPT_SP_REGS + 255)
#  define REG_V150            (XCPT_SP_REGS + 256)
#  define REG_V151            (XCPT_SP_REGS + 257)
#  define REG_V152            (XCPT_SP_REGS + 258)
#  define REG_V153            (XCPT_SP_REGS + 259)
#  define REG_V154            (XCPT_SP_REGS + 260)
#  define REG_V155            (XCPT_SP_REGS + 261)
#  define REG_V156            (XCPT_SP_REGS + 262)
#  define REG_V157            (XCPT_SP_REGS + 263)
#  define REG_V140            (XCPT_SP_REGS + 264)
#  define REG_V141            (XCPT_SP_REGS + 265)
#  define REG_V142            (XCPT_SP_REGS + 266)
#  define REG_V143            (XCPT_SP_REGS + 267)
#  define REG_V144            (XCPT_SP_REGS + 268)
#  define REG_V145            (XCPT_SP_REGS + 269)
#  define REG_V146            (XCPT_SP_REGS + 270)
#  define REG_V147            (XCPT_SP_REGS + 271)
#  define REG_V130            (XCPT_SP_REGS + 272)
#  define REG_V131            (XCPT_SP_REGS + 273)
#  define REG_V132            (XCPT_SP_REGS + 274)
#  define REG_V133            (XCPT_SP_REGS + 275)
#  define REG_V134            (XCPT_SP_REGS + 276)
#  define REG_V135            (XCPT_SP_REGS + 277)
#  define REG_V136            (XCPT_SP_REGS + 278)
#  define REG_V137            (XCPT_SP_REGS + 279)
#  define REG_V120            (XCPT_SP_REGS + 280)
#  define REG_V121            (XCPT_SP_REGS + 281)
#  define REG_V122            (XCPT_SP_REGS + 282)
#  define REG_V123            (XCPT_SP_REGS + 283)
#  define REG_V124            (XCPT_SP_REGS + 284)
#  define REG_V125            (XCPT_SP_REGS + 285)
#  define REG_V126            (XCPT_SP_REGS + 286)
#  define REG_V127            (XCPT_SP_REGS + 287)
#  define REG_V110            (XCPT_SP_REGS + 288)
#  define REG_V111            (XCPT_SP_REGS + 289)
#  define REG_V112            (XCPT_SP_REGS + 290)
#  define REG_V113            (XCPT_SP_REGS + 291)
#  define REG_V114            (XCPT_SP_REGS + 292)
#  define REG_V115            (XCPT_SP_REGS + 293)
#  define REG_V116            (XCPT_SP_REGS + 294)
#  define REG_V117            (XCPT_SP_REGS + 295)
#  define REG_V100            (XCPT_SP_REGS + 296)
#  define REG_V101            (XCPT_SP_REGS + 297)
#  define REG_V102            (XCPT_SP_REGS + 298)
#  define REG_V103            (XCPT_SP_REGS + 299)
#  define REG_V104            (XCPT_SP_REGS + 300)
#  define REG_V105            (XCPT_SP_REGS + 301)
#  define REG_V106            (XCPT_SP_REGS + 302)
#  define REG_V107            (XCPT_SP_REGS + 303)
#  define REG_V90             (XCPT_SP_REGS + 304)
#  define REG_V91             (XCPT_SP_REGS + 305)
#  define REG_V92             (XCPT_SP_REGS + 306)
#  define REG_V93             (XCPT_SP_REGS + 307)
#  define REG_V94             (XCPT_SP_REGS + 308)
#  define REG_V95             (XCPT_SP_REGS + 309)
#  define REG_V96             (XCPT_SP_REGS + 310)
#  define REG_V97             (XCPT_SP_REGS + 311)
#  define REG_V80             (XCPT_SP_REGS + 312)
#  define REG_V81             (XCPT_SP_REGS + 313)
#  define REG_V82             (XCPT_SP_REGS + 314)
#  define REG_V83             (XCPT_SP_REGS + 315)
#  define REG_V84             (XCPT_SP_REGS + 316)
#  define REG_V85             (XCPT_SP_REGS + 317)
#  define REG_V86             (XCPT_SP_REGS + 318)
#  define REG_V87             (XCPT_SP_REGS + 319)
#  define REG_V70             (XCPT_SP_REGS + 320)
#  define REG_V71             (XCPT_SP_REGS + 321)
#  define REG_V72             (XCPT_SP_REGS + 322)
#  define REG_V73             (XCPT_SP_REGS + 323)
#  define REG_V74             (XCPT_SP_REGS + 324)
#  define REG_V75             (XCPT_SP_REGS + 325)
#  define REG_V76             (XCPT_SP_REGS + 326)
#  define REG_V77             (XCPT_SP_REGS + 327)
#  define REG_V60             (XCPT_SP_REGS + 328)
#  define REG_V61             (XCPT_SP_REGS + 329)
#  define REG_V62             (XCPT_SP_REGS + 330)
#  define REG_V63             (XCPT_SP_REGS + 331)
#  define REG_V64             (XCPT_SP_REGS + 332)
#  define REG_V65             (XCPT_SP_REGS + 333)
#  define REG_V66             (XCPT_SP_REGS + 334)
#  define REG_V67             (XCPT_SP_REGS + 335)
#  define REG_V50             (XCPT_SP_REGS + 336)
#  define REG_V51             (XCPT_SP_REGS + 337)
#  define REG_V52             (XCPT_SP_REGS + 338)
#  define REG_V53             (XCPT_SP_REGS + 339)
#  define REG_V54             (XCPT_SP_REGS + 340)
#  define REG_V55             (XCPT_SP_REGS + 341)
#  define REG_V56             (XCPT_SP_REGS + 342)
#  define REG_V57             (XCPT_SP_REGS + 343)
#  define REG_V40             (XCPT_SP_REGS + 344)
#  define REG_V41             (XCPT_SP_REGS + 345)
#  define REG_V42             (XCPT_SP_REGS + 346)
#  define REG_V43             (XCPT_SP_REGS + 347)
#  define REG_V44             (XCPT_SP_REGS + 348)
#  define REG_V45             (XCPT_SP_REGS + 349)
#  define REG_V46             (XCPT_SP_REGS + 350)
#  define REG_V47             (XCPT_SP_REGS + 351)
#  define REG_V30             (XCPT_SP_REGS + 352)
#  define REG_V31             (XCPT_SP_REGS + 353)
#  define REG_V32             (XCPT_SP_REGS + 354)
#  define REG_V33             (XCPT_SP_REGS + 355)
#  define REG_V34             (XCPT_SP_REGS + 356)
#  define REG_V35             (XCPT_SP_REGS + 357)
#  define REG_V36             (XCPT_SP_REGS + 358)
#  define REG_V37             (XCPT_SP_REGS + 359)
#  define REG_V20             (XCPT_SP_REGS + 360)
#  define REG_V21             (XCPT_SP_REGS + 361)
#  define REG_V22             (XCPT_SP_REGS + 362)
#  define REG_V23             (XCPT_SP_REGS + 363)
#  define REG_V24             (XCPT_SP_REGS + 364)
#  define REG_V25             (XCPT_SP_REGS + 365)
#  define REG_V26             (XCPT_SP_REGS + 366)
#  define REG_V27             (XCPT_SP_REGS + 367)
#  define REG_V10             (XCPT_SP_REGS + 368)
#  define REG_V11             (XCPT_SP_REGS + 369)
#  define REG_V12             (XCPT_SP_REGS + 370)
#  define REG_V13             (XCPT_SP_REGS + 371)
#  define REG_V14             (XCPT_SP_REGS + 372)
#  define REG_V15             (XCPT_SP_REGS + 373)
#  define REG_V16             (XCPT_SP_REGS + 374)
#  define REG_V17             (XCPT_SP_REGS + 375)
#  define REG_V00             (XCPT_SP_REGS + 376)
#  define REG_V01             (XCPT_SP_REGS + 377)
#  define REG_V02             (XCPT_SP_REGS + 378)
#  define REG_V03             (XCPT_SP_REGS + 379)
#  define REG_V04             (XCPT_SP_REGS + 380)
#  define REG_V05             (XCPT_SP_REGS + 381)
#  define REG_V06             (XCPT_SP_REGS + 382)
#  define REG_V07             (XCPT_SP_REGS + 383)
#  define XCPT_VPU_REGS       384
#else
#  define XCPT_VPU_REGS       0
#endif

#define REG_MODI              (XCPT_SP_REGS + XCPT_VPU_REGS + 0)
#define REG_MODG              (XCPT_SP_REGS + XCPT_VPU_REGS + 1)
#define REG_MODE              (XCPT_SP_REGS + XCPT_VPU_REGS + 2)
#define REG_MODD              (XCPT_SP_REGS + XCPT_VPU_REGS + 3)
#define REG_MODC              (XCPT_SP_REGS + XCPT_VPU_REGS + 4)
#define REG_R56               (XCPT_SP_REGS + XCPT_VPU_REGS + 5)
#define REG_R57               (XCPT_SP_REGS + XCPT_VPU_REGS + 6)
#define REG_R58               (XCPT_SP_REGS + XCPT_VPU_REGS + 7)
#define REG_R59               (XCPT_SP_REGS + XCPT_VPU_REGS + 8)
#define REG_R60               (XCPT_SP_REGS + XCPT_VPU_REGS + 9)
#define REG_R61               (XCPT_SP_REGS + XCPT_VPU_REGS + 10)
#define REG_R62               (XCPT_SP_REGS + XCPT_VPU_REGS + 11)
#define REG_R63               (XCPT_SP_REGS + XCPT_VPU_REGS + 12)
#define REG_R48               (XCPT_SP_REGS + XCPT_VPU_REGS + 13)
#define REG_R49               (XCPT_SP_REGS + XCPT_VPU_REGS + 14)
#define REG_R50               (XCPT_SP_REGS + XCPT_VPU_REGS + 15)
#define REG_R51               (XCPT_SP_REGS + XCPT_VPU_REGS + 16)
#define REG_R52               (XCPT_SP_REGS + XCPT_VPU_REGS + 17)
#define REG_R53               (XCPT_SP_REGS + XCPT_VPU_REGS + 18)
#define REG_R54               (XCPT_SP_REGS + XCPT_VPU_REGS + 19)
#define REG_R55               (XCPT_SP_REGS + XCPT_VPU_REGS + 20)
#define REG_R40               (XCPT_SP_REGS + XCPT_VPU_REGS + 21)
#define REG_R41               (XCPT_SP_REGS + XCPT_VPU_REGS + 22)
#define REG_R42               (XCPT_SP_REGS + XCPT_VPU_REGS + 23)
#define REG_R43               (XCPT_SP_REGS + XCPT_VPU_REGS + 24)
#define REG_R44               (XCPT_SP_REGS + XCPT_VPU_REGS + 25)
#define REG_R45               (XCPT_SP_REGS + XCPT_VPU_REGS + 26)
#define REG_R46               (XCPT_SP_REGS + XCPT_VPU_REGS + 27)
#define REG_R47               (XCPT_SP_REGS + XCPT_VPU_REGS + 28)
#define REG_R32               (XCPT_SP_REGS + XCPT_VPU_REGS + 29)
#define REG_R33               (XCPT_SP_REGS + XCPT_VPU_REGS + 30)
#define REG_R34               (XCPT_SP_REGS + XCPT_VPU_REGS + 31)
#define REG_R35               (XCPT_SP_REGS + XCPT_VPU_REGS + 32)
#define REG_R36               (XCPT_SP_REGS + XCPT_VPU_REGS + 33)
#define REG_R37               (XCPT_SP_REGS + XCPT_VPU_REGS + 34)
#define REG_R38               (XCPT_SP_REGS + XCPT_VPU_REGS + 35)
#define REG_R39               (XCPT_SP_REGS + XCPT_VPU_REGS + 36)
#define REG_R24               (XCPT_SP_REGS + XCPT_VPU_REGS + 37)
#define REG_R25               (XCPT_SP_REGS + XCPT_VPU_REGS + 38)
#define REG_R26               (XCPT_SP_REGS + XCPT_VPU_REGS + 39)
#define REG_R27               (XCPT_SP_REGS + XCPT_VPU_REGS + 40)
#define REG_R28               (XCPT_SP_REGS + XCPT_VPU_REGS + 41)
#define REG_R29               (XCPT_SP_REGS + XCPT_VPU_REGS + 42)
#define REG_R30               (XCPT_SP_REGS + XCPT_VPU_REGS + 43)
#define REG_R31               (XCPT_SP_REGS + XCPT_VPU_REGS + 44)
#define REG_R16               (XCPT_SP_REGS + XCPT_VPU_REGS + 45)
#define REG_R17               (XCPT_SP_REGS + XCPT_VPU_REGS + 46)
#define REG_R18               (XCPT_SP_REGS + XCPT_VPU_REGS + 47)
#define REG_R19               (XCPT_SP_REGS + XCPT_VPU_REGS + 48)
#define REG_R20               (XCPT_SP_REGS + XCPT_VPU_REGS + 49)
#define REG_R21               (XCPT_SP_REGS + XCPT_VPU_REGS + 50)
#define REG_R22               (XCPT_SP_REGS + XCPT_VPU_REGS + 51)
#define REG_R23               (XCPT_SP_REGS + XCPT_VPU_REGS + 52)
#define REG_R8                (XCPT_SP_REGS + XCPT_VPU_REGS + 53)
#define REG_R9                (XCPT_SP_REGS + XCPT_VPU_REGS + 54)
#define REG_R10               (XCPT_SP_REGS + XCPT_VPU_REGS + 55)
#define REG_R11               (XCPT_SP_REGS + XCPT_VPU_REGS + 56)
#define REG_R12               (XCPT_SP_REGS + XCPT_VPU_REGS + 57)
#define REG_R13               (XCPT_SP_REGS + XCPT_VPU_REGS + 58)
#define REG_R14               (XCPT_SP_REGS + XCPT_VPU_REGS + 59)
#define REG_R15               (XCPT_SP_REGS + XCPT_VPU_REGS + 60)
#define REG_R0                (XCPT_SP_REGS + XCPT_VPU_REGS + 61)
#define REG_R1                (XCPT_SP_REGS + XCPT_VPU_REGS + 62)
#define REG_R2                (XCPT_SP_REGS + XCPT_VPU_REGS + 63)
#define REG_R3                (XCPT_SP_REGS + XCPT_VPU_REGS + 64)
#define REG_R4                (XCPT_SP_REGS + XCPT_VPU_REGS + 65)
#define REG_R5                (XCPT_SP_REGS + XCPT_VPU_REGS + 66)
#define REG_R6                (XCPT_SP_REGS + XCPT_VPU_REGS + 67)
#define REG_R7                (XCPT_SP_REGS + XCPT_VPU_REGS + 68)
#define REG_RETREGN           (XCPT_SP_REGS + XCPT_VPU_REGS + 69)
#define REG_RETREG            (XCPT_SP_REGS + XCPT_VPU_REGS + 70)
#define REG_RETREG_TEMP       (XCPT_SP_REGS + XCPT_VPU_REGS + 71)
#define REG_RETREGI           (XCPT_SP_REGS + XCPT_VPU_REGS + 72)
#define REG_MODVL0            (XCPT_SP_REGS + XCPT_VPU_REGS + 73)
#define REG_MODVL1            (XCPT_SP_REGS + XCPT_VPU_REGS + 74)
#define REG_MODVLL            (XCPT_SP_REGS + XCPT_VPU_REGS + 75)
#define REG_MODVFP            (XCPT_SP_REGS + XCPT_VPU_REGS + 76)
#define XCPT_GEN_REGS         77

/* The total number of registers is saved on the stack */

#define XCPTCONTEXT_REGS    (XCPT_SP_REGS + XCPT_VPU_REGS + XCPT_GEN_REGS)
#define XCPTCONTEXT_SIZE    (4 * XCPTCONTEXT_REGS)

/****************************************************************************
 * Public Types
 ****************************************************************************/

/****************************************************************************
 * Inline functions
 ****************************************************************************/

/****************************************************************************
 * Public Data
 ****************************************************************************/

/****************************************************************************
 * Public Function Prototypes
 ****************************************************************************/

#endif /* __ARCH_CEVA_INCLUDE_XM6_REG_H */
